// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_oUh9sslDz_5sTrjESjpp2HoMudCTNGU',
    appId: '1:817075295725:web:0fa1c7ccaddfee96a5c3e4',
    messagingSenderId: '817075295725',
    projectId: 'study-app-test-3c4be',
    authDomain: 'study-app-test-3c4be.firebaseapp.com',
    storageBucket: 'study-app-test-3c4be.appspot.com',
    measurementId: 'G-BKYYYEFW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnJ9YpHqbA5ZmGzwywktAXC6o81NFMUbo',
    appId: '1:817075295725:android:63602fc3f33f928ea5c3e4',
    messagingSenderId: '817075295725',
    projectId: 'study-app-test-3c4be',
    storageBucket: 'study-app-test-3c4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4PHsLvs8RweuOAQtJOWni_WHCVkn3c8',
    appId: '1:817075295725:ios:1985c61145a61951a5c3e4',
    messagingSenderId: '817075295725',
    projectId: 'study-app-test-3c4be',
    storageBucket: 'study-app-test-3c4be.appspot.com',
    iosClientId: '817075295725-hm3j2b2b865jtkt27hrvie0lcfpn355r.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo4PHsLvs8RweuOAQtJOWni_WHCVkn3c8',
    appId: '1:817075295725:ios:1985c61145a61951a5c3e4',
    messagingSenderId: '817075295725',
    projectId: 'study-app-test-3c4be',
    storageBucket: 'study-app-test-3c4be.appspot.com',
    iosClientId: '817075295725-hm3j2b2b865jtkt27hrvie0lcfpn355r.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
